### ISSUE TITLE
项目无法启动

### ISSUE THREAD

**Issue by Qiuzero** [zhaodeezhu/xioo-docs#6]
项目无法启动
![image](https://user-images.githubusercontent.com/59104067/187876222-fa028f3c-e4fd-46e2-a2b2-03df676766bb.png)

**Comment by zhaodeezhu** [comment]
是因为我的域名备案过期了，我引用drawio是使用CDN的方式引用，所以暂时无法启动了。
实际上，drawio的部分是使用的这个项目 https://github.com/zhaodeezhu/drawio-node
如果要本地启动的话可以将两个项目都启动起来，然后将相应的域名 https://drawio.xiooshow.com换成http://localhost:2301即可
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/58294623/187878983-44f258c7-303f-4bf7-886e-abbbf16561e1.png">
给您带来了困扰，非常抱歉，如果遇到问题，可以再联系我。

**Comment by zhaodeezhu** [comment]
暂时将体验地址换成了IP，项目已经可以启动了，欢迎体验
