### ISSUE TITLE
触发新建时，默认新建类型不生效，存在旧数据。

### ISSUE THREAD

**Issue by Qiuzero** [zhaodeezhu/xioo-docs#8]
![image](https://user-images.githubusercontent.com/59104067/191410357-315a7b25-2803-4175-87f8-4d7d6138b6d5.png)
你好，请教个问题，目前编辑器内部集成drawio，新建编辑没有任何问题，然后我这边加了一个功能，通过某些条件自动触发新建，出现了 xioo-node里配置的默认新建类型不生效，并且，存在旧值，而不是选择模板的新建页面，类似编辑一样。请教一下，大概是什么原因导致的。

**Comment by Qiuzero** [comment]
解决了 settimeout两秒就行

**Comment by zhaodeezhu** [comment]
应该是drawio还没有加载完成，所以自动触发新建发消息的时候drawio没有接受到值，导致不能完成这个流程。settimeout治标不治本，如果drawio在加载比较慢或者缓存失效的情况下，还是会出问题，要找到drawio已经加载完以后时机以后在去新建才行，你可以先看下，如果找不到这个时机，我可以帮你在添加一个类似于三次握手的过程，能保证你给他的消息他可以100%的收到并执行。

**Comment by Qiuzero** [comment]
> 应该是drawio还没有加载完成，所以自动触发新建发消息的时候drawio没有接受到值，导致不能完成这个流程。settimeout治标不治本，如果drawio在加载比较慢或者缓存失效的情况下，还是会出问题，要找到drawio已经加载完以后时机以后在去新建才行，你可以先看下，如果找不到这个时机，我可以帮你在添加一个类似于三次握手的过程，能保证你给他的消息他可以100%的收到并执行。

 好的 感谢 我再试一下
